let dados = [
    {
        nome: "Olinda",
        descricao: "Patrimônio Mundial da UNESCO, conhecida por seus casarões coloniais e carnaval.",
        link: "https://pt.wikipedia.org/wiki/Olinda",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Montagem_Olinda_2021.jpg/270px-Montagem_Olinda_2021.jpg",
        estado: "Pernambuco",
        Fundacao: 1535,
        festas: "Carnaval de Olinda, São João",
        Personalidades: "Cartola",
        pontosTuristicos: "Sítio Histórico de Olinda, Alto da Sé",
        tags: "colonial, carnaval, patrimônio mundial"
    },
    {
        nome: "Paraty",
        descricao: "Charmosa cidade colonial com ruas de pedra e casarões históricos.",
        link: "https://pt.wikipedia.org/wiki/Paraty",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/be/Paraty_05.JPG/270px-Paraty_05.JPG",
        estado: "Rio de Janeiro",
        Fundacao: 1667,
        festas: "Festival de Paraty, Festa de Nossa Senhora dos Remédios",
        Personalidades: "",
        pontosTuristicos: "Centro Histórico, Trilha do Caminho do Ouro",
        tags: "colonial, histórico, natureza"
    },
    {
        nome: "Ouro Preto",
        descricao: "Patrimônio Mundial da UNESCO, conhecida por sua arquitetura barroca e pela importância na mineração do ouro.",
        link: "https://pt.wikipedia.org/wiki/Ouro_Preto",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Conjunto_arquitet%C3%B4nico_e_urban%C3%ADstico_de_Ouro_Preto.JPG/189px-Conjunto_arquitet%C3%B4nico_e_urban%C3%ADstico_de_Ouro_Preto.JPG",
        estado: "Minas Gerais",
        Fundacao: 1711,
        festas: "Congresso de Confrarias, Folia de Reis",
        Personalidades: "Aleijadinho",
        pontosTuristicos: "Igreja de São Francisco de Assis, Museu da Inconfidência",
        tags: "barroco, ouro, patrimônio mundial"
    },
    {
        nome: "Tiradentes",
        descricao: "Charmosa cidade histórica com ruas de pedra e casarões coloniais.",
        link: "https://pt.wikipedia.org/wiki/Tiradentes_(Minas_Gerais)",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Tiradentes_-_Minas_Gerais_-_Brasil._%2815463465202%29.jpg/270px-Tiradentes_-_Minas_Gerais_-_Brasil._%2815463465202%29.jpg",
        estado: "Minas Gerais",
        Fundacao: 1718,
        festas: "Festival de Inverno de Tiradentes",
        Personalidades: "",
        pontosTuristicos: "Largo dos Coqueiros, Museu de Sant'Anna",
        tags: "colonial, ouro, dentista"
    },
    {
        nome: "Salvador",
        descricao: "Primeira capital do Brasil, com um rico centro histórico e diversas manifestações culturais.",
        link: "https://pt.wikipedia.org/wiki/Salvador",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Entardecer_elevedor_lacerda.jpg/125px-Entardecer_elevedor_lacerda.jpg",
        estado: "Bahia",
        Fundacao: 1549,
        festas: "Carnaval de Salvador, São João",
        Personalidades: "Caetano Veloso, Gilberto Gil",
        pontosTuristicos: "Pelourinho, Elevador Lacerda",
        tags: "colonial, afro-brasileiro, carnaval"
    },
    {
        nome: "São Luís",
        descricao: "Cidade com forte influência francesa, com arquitetura única e rica história cultural.",
        link: "https://pt.wikipedia.org/wiki/S%C3%A3o_Lu%C3%ADs_(Maranh%C3%A3o)",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/S%C3%A3o_Luis_do_Maranh%C3%A3o-Montagem.jpg/270px-S%C3%A3o_Luis_do_Maranh%C3%A3o-Montagem.jpg",
        estado: "Maranhão",
        Fundacao: 1612,
        festas: "Bumba-meu-boi",
        Personalidades: "",
        pontosTuristicos: "Centro Histórico, Lendas Maranhenses",
        tags: "francesa, bumba-meu-boi"
    },
    {
        nome: "Petrópolis",
        descricao: "Conhecida como a Cidade Imperial, foi a segunda capital do Império do Brasil e possui uma arquitetura inspirada nos Alpes europeus.",
        link: "https://pt.wikipedia.org/wiki/Petrópolis",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Montagem_Petr%C3%B3polis.jpg/270px-Montagem_Petr%C3%B3polis.jpg",
        estado: "Rio de Janeiro",
        Fundacao: 1843,
        festas: "Carnaval de Petrópolis",
        Personalidades: "Dom Pedro II",
        pontosTuristicos: "Palácio de Cristal, Museu Imperial",
        tags: "imperial, alemã, montanhas"
    },
    {
        nome: "Porto Seguro",
        descricao: "Local de chegada dos portugueses ao Brasil, com um rico patrimônio histórico e cultural.",
        link: "https://pt.wikipedia.org/wiki/Porto_Seguro",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Porto_Seguro.1.jpg/270px-Porto_Seguro.1.jpg",
        estado: "Bahia",
        Fundacao: 1500,
        festas: "Festival de Verão de Porto Seguro",
        Personalidades: "",
        pontosTuristicos: "Marco do Descobrimento, Passarela do Álcool",
        tags: "descobrimento, praia, histórico"
    },
    {
        nome: "São João del-Rei",
        descricao: "Cidade histórica com rica arquitetura barroca e importante papel no ciclo do ouro.",
        link: "https://pt.wikipedia.org/wiki/São_João_del-Rei",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Centro_Hist%C3%B3rico_S%C3%A3o_Jo%C3%A3o_del-Rei-Thais_Andressa_-_2019-12-18.jpg/270px-Centro_Hist%C3%B3rico_S%C3%A3o_Jo%C3%A3o_del-Rei-Thais_Andressa_-_2019-12-18.jpg",
        estado: "Minas Gerais",
        Fundacao: 1713,
        festas: "Festa de Nossa Senhora do Carmo",
        Personalidades: "",
        pontosTuristicos: "Basílica do Senhor Bom Jesus de Matosinhos, Museu do Oratório",
        tags: "barroco, ouro, religioso"
    },
    {
        nome: "Belém",
        descricao: "Capital paraense, com rica história e cultura, marcada pela influência indígena e pela Amazônia.",
        link: "https://pt.wikipedia.org/wiki/Bel%C3%A9m_(Par%C3%A1)",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/L1010748-L1010765_copie_%28cropped%29.jpg/278px-L1010748-L1010765_copie_%28cropped%29.jpg",
        estado: "Pará",
        Fundacao: 1616,
        festas: "Círio de Nazaré",
        Personalidades: "",
        pontosTuristicos: "Mercado do Ver-o-Peso",
        tags: "amazônia, indígena, colonial"
    },
    {
        nome: "Santarém",
        descricao: "Cidade histórica do Pará, com forte influência portuguesa e um centro histórico bem preservado.",
        link: "https://pt.wikipedia.org/wiki/Santar%C3%A9m_(Par%C3%A1)",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Santar%C3%A9m_montagem.jpg/270px-Santar%C3%A9m_montagem.jpg",
        estado: "Pará",
        Fundacao: 1616,
        festas: "Festival Folclórico de Santarém",
        Personalidades: "",
        pontosTuristicos: "Forte de São José de Maranhão",
        tags: "colonial, portuguesa, amazônia"
    },
    {
        nome: "Manaus",
        descricao: "Capital amazonense, conhecida como a 'Paris dos Trópicos', com arquitetura eclética e rica história.",
        link: "https://pt.wikipedia.org/wiki/Manaus",
        foto: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Skyline-de-Manaus.jpg/278px-Skyline-de-Manaus.jpg",
        estado: "Amazonas",
        Fundacao: 1669,
        festas: "Festival de Parintins",
        Personalidades: "",
        pontosTuristicos: "Teatro Amazonas",
        tags: "amazônia, borracha, eclética"
    }        
];
